### ISSUE TITLE
Shift-Tab not working

### ISSUE THREAD

**Issue by PROGRAM-IX** [svexican/cheeky#10]
@svexican I thought I implemented it the way you suggested, and it seemed fine? But it's not working for me now. Just flicks the selector back to the first option. Is it working for you at all? Happy to try and fix if not, or can just submit a quick PR removing the Shift-Tab behaviour. (Tab works fine.)

(An issue seemed to be the place for this, if you have a different place we can discuss there.)

**Comment by svexican** [comment]
@PROGRAM-IX this is the right place  :D

I just checked. Sadly, it works well on my side (meaning it'll be harder to find the bug). 
Check using `xev` or some similar utility to see the keycode you get when pressing `Shift + Tab`. I get:
```
KeyRelease event, serial 33, synthetic NO, window 0x2200001,
    root 0xda, subw 0x0, time 127250183, (713,204), root:(1705,618),
    state 0x1, keycode 23 (keysym 0xfe20, ISO_Left_Tab), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Also, you should check you don't have any funky configuration...

**Comment by PROGRAM-IX** [comment]
Good, at least I didn't submit a totally busted change.

Did some more testing on a different computer, xev shows the expected
output (same as yours) and the master branch works perfectly to scroll back
through with Shift-Tab. Weird. I'll have another look on the computer I was
using when I had that issue and get back to you. Worst case, I'll probably
have to add another key option, which isn't too bad. :)
​

**Comment by PROGRAM-IX** [comment]
Back on the original computer now and xev is telling me that Shift+Tab is indeed ISO_Left_Tab. When I re-enable the behaviour, it works just fine with no changes from what's in master. Wonder what was wrong that time. I've had some trouble with keyboard mappings before (Irish locales can be a pain at times on Linux, even though in theory they are 99% the same as the UK).

Anyway, guess I'll close this, happily, and maybe some other time if I observe the issue again, I'll think to run xev and find the source.

**Comment by svexican** [comment]
Let me know when/if you find the bug... I'm a bit curious.

**Comment by PROGRAM-IX** [comment]
I will do. I wonder if I screwed something up in the branch at that time,
and fixed it since without realising. It's hard to know, but I'll be
keeping an eye out for it since I use the switcher so much now! :)
