### ISSUE TITLE
focus not changed in multimonitor setup

### ISSUE THREAD

**Issue by gizmomogwai** [svexican/cheeky#13]
hi ... i really love the cheeky idea.
it works easily enough, but for me the focus is not changed, when i change to a client on another window.
how can i adjust cheeky to do that for me?

**Comment by gizmomogwai** [comment]
sorry about the issue, i just rechecked and the focus is changed, but the mousepointer stays at the old place, which is even quite all right! thanks for this really nice plugin!

**Comment by svexican** [comment]
I'm glad you like it! enjoy! :satisfied:

**Comment by svexican** [comment]
Let me think about the moving of the cursor... it might be a good/natural idea. I could add it as an option. :smiley:
